export default [
  {
    id: 1,
    routeId: "/nadogradnja",
    img: "materijal/Nadogradnja trepavica/nadogradnja.jpg",
    title: "SVILENE TREPAVICE",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
   },
  {
    id: 2,
    routeId: "/depilacija",
    img: "materijal/vosak/vosak1.png",
    title: "DEPILACIJA",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 3,
    routeId: "/tetoviranje",
    img: "materijal/tetoviranje/tetoviranje.jpg",
    title: "TRAJNA ŠMINKA",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 4,
    routeId: "/laser",
    img: "materijal/Laser/laser.jpg",
    title: "KAVITACIJA",
    text: "Kavitacija je savremena metoda kojom se smanjuje koncentracija masnog tkiva. Kavitacija se sprovodi u seriji od nekoliko tretmana a posle kavitacija tretmana potrebno je uraditi nekoliko limfnih drenaža kako bi se razbijene masne ćelije što lakše izbacile iz organizma.",
    button: "",
  },
  {
    id: 5,
    routeId: "/nokti",
    img: "materijal/Nokti/nokti.jpg",
    title: "MANIKIR",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 6,
    routeId: "/sminka",
    img: "materijal/Sminka/sminka.png",
    title: "ŠMINKA",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    button: "",
  },
];
