export default [
  {
    id: 1,
    routeId: "/nadogradnja",
    img: "materijal/Nadogradnja trepavica/nadogradnja.jpg",
    title: "Nadogradnja Trepavia",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
   },
  {
    id: 2,
    routeId: "/depilacija",
    img: "materijal/vosak/vosak1.png",
    title: "Depilacija Voskom",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 3,
    routeId: "/tetoviranje",
    img: "materijal/tetoviranje/tetoviranje.jpg",
    title: "Tetoviranje Obrva",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 4,
    routeId: "/laser",
    img: "materijal/Laser/laser.jpg",
    title: "Laser",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 5,
    routeId: "/nokti",
    img: "materijal/Nokti/nokti.jpg",
    title: "Manikir",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    button: "",
  },
  {
    id: 6,
    routeId: "/sminka",
    img: "materijal/Sminka/sminka.png",
    title: "Sminka",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
    button: "",
  },
];
